name: CI - Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  tests:
    name : Backend Test
    runs-on: ubuntu-latest

    steps:
    - name : Checkout Backend
      uses: actions/checkout@v4
      with:
        path: backend
      
    - name: Use Node.js 
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        
    - name: Install dependecies   
      run: npm ci
      working-directory: ./backend
      
    - name : Build 
      run: npm run build --if-present
      working-directory: ./backend
    
    - name : Run Tests
      run: npm test
      working-directory: ./backend
